version: "3.9"

name: devops-lab

services:

  sonarqube:
    image: sonarqube:lts-community
    restart: unless-stopped

    ports:
      - "9000:9000"

    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"

    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

    networks:
      - devops-network

  jenkins:
    image: jenkins/jenkins:lts-jdk21
    restart: unless-stopped

    ports:
      - "8081:8080"
      - "50000:50000"

    volumes:
      - jenkins_home:/var/jenkins_home

    networks:
      - devops-network

volumes:

  sonarqube_data:

  sonarqube_logs:

  sonarqube_extensions:

  jenkins_home:

networks:

  devops-network:
    driver: bridge