name: React CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-test:

    runs-on:
      - self-hosted
      - windows

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Show Node version
        run: node -v

      - name: Show npm version
        run: npm -v

      - name: Show current directory
        run: pwd

      - name: Show environment
        run: set

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:run

      - name: Build React application
        run: npm run build

      - name: Upload production artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: dist